version: '3.1'

services:
    main:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - PORT=3000
        ports:
            - "3000:3000"
        volumes:
            - ./wp-content:/var/www/html/wp-content
        env_file:
            - .env